version: '3'
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ./main
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
